# Generated by Django 3.2.8 on 2021-10-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('fuel_consumption', models.FloatField(help_text='km/lt')),
                ('distance_traveled', models.FloatField(default=0)),
                ('fuel_consumed', models.FloatField(default=0)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities.city')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_arrived', to='cities.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_send', to='cities.city')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
