# Generated by Django 3.2.8 on 2021-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_traveled',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_consumed',
            field=models.FloatField(default=0, help_text='lts'),
        ),
    ]
