# Generated by Django 3.2.8 on 2021-10-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('city_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_1', to='cities.city')),
                ('city_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_2', to='cities.city')),
            ],
        ),
    ]
