# Generated by Django 3.2.8 on 2021-10-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together={('city_1', 'city_2')},
        ),
    ]
