# Generated by Django 3.2.8 on 2021-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20211029_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.FloatField(help_text='kms'),
        ),
    ]
